### ISSUE TITLE
Are there plans to support IOS and Android platforms

### ISSUE THREAD

**Issue by limocute** [AlzPatz/yak2d#1]
Hello, I'm using yak2d to make a small game. Does yak2d plan to support IOS and Android platforms? I see veldrid supports it. Do you plan to support it.

**Comment by AlzPatz** [comment]
Hello - It’s great to hear you are using Yak2D. I was not planning to support iOS and Android, but I do not imagine the changes required are major. I suppose it would require adding support for touch screen input, and also adding Open GL ES shaders for android. I might be able to take a look at these, but my time is a little stretched in other areas and I haven’t got an iOS dev environment at the moment. Is this support crucial for you, ie is your game mobile only or were you starting with desktop first?

**Comment by limocute** [comment]
Hello, my game target platform is PC and mobile. I am currently making PC functions. If yak2d supports mobile platforms, I don’t need to find another mobile platform solution. If possible, I will look forward to yak2d supporting mobile  platform

**Comment by AlzPatz** [comment]
I will close this issue for now, but will update when any progress is made on this topic.
