### ISSUE TITLE
The drawstring method does not handle Emoji properly

### ISSUE THREAD

**Issue by limocute** [AlzPatz/yak2d#4]
Hi,I find that the drawstring method can't handle Emoji correctly. My idea is that
 
The drawstring method needs to check whether the parameter [text] contains Emoji. If the character to be drawn is Emoji, it needs to be drawn correctly from the font that supports Emoji . In addition, the yak2d.font project may also need to add a font that supports Emoji .

Maybe you have a better solution!

**Comment by AlzPatz** [comment]
Hi. I must admit I am not an expert on fonts. My font drawing implementation was always supposed to be simple bitmap fonts. However, I have had my eye on FontStashSharp ([https://github.com/rds1983/FontStashSharp](https://github.com/rds1983/FontStashSharp)). I may replace font rendering with this or enable an option to use it. I believe it handles emoji OK.

**Comment by AlzPatz** [comment]
It would help if you could perhaps give me an example of a font (ttf?) and emoji (character string?) you would like to render? Thanks!

**Comment by limocute** [comment]
Hello, I have uploaded TTF font and Emoji string to the repository [emojitest](https://github.com/limocute/emojitest).

ttf font is [Segoe UI Emoji.ttf] of windows 10 

The Emoji character tested is:
```
draw.DrawString(_drawStage,
                             CoordinateSpace.Screen,
                             "Test Emoji 🎄😃😜🙉😉😍😝🙅🙊✂✈✊🚄🚑🆗♻⚽🍚🎄",
                             Colour.IndianRed,
                             18.0f,
                             new Vector2(-430.0f, 220.0f),
                             TextJustify.Left,
                             0.5f,
                             0);
```

**Comment by AlzPatz** [comment]
Hi. I have submitted a pull request to your repo. It implements FontStashSharp font rendering (which supports Emojiis) using the DrawStage rendering stage already in Yak2D. I may in the future modify Yak2D to either replace the Font rendering with FontStashSharp or expand the existing font system to cover Emojiis. 

![image](https://user-images.githubusercontent.com/3255197/103353307-6f739280-4aa0-11eb-926d-b7279366f58a.png)

**Comment by limocute** [comment]
Thank you for your help. I'm currently using yak2d to replace the game made by D2D. So far, the work is very smooth and I like yak2d very much
