### ISSUE TITLE
How to fill texture to circular

### ISSUE THREAD

**Issue by limocute** [AlzPatz/yak2d#6]
Hello,
How do I map an image to a circle?
I want to map an image into a circle, but I only see the [DrawColouredPoly] method.

**Comment by AlzPatz** [comment]
Hello! I hope you are well.

You have a couple of options here. 

yak2D's 'lowest level' drawing process is for the user to submit a suitable DrawRequest struct to the draw queue of a DrawStage. The DrawRequest contains a collection of vertices, an index list describing how to construct the triangles from this list of vertices and then additional information including the type of rendering (solid colour, textured, dual textured) and texture coordinates (this is done in the project Draw_PolygonsFromVertices in the yak2D samples repo)

The reason I mention this, is that you can simply define your own textured circle drawing method to help you generate a suitable DrawRequest struct.

However, yak2D also includes some higher level helper functions, including the DrawColouredPoly method you have located. These methods simply generate the DrawRequest required and submit it to the DrawStage queue.

There are two types of Drawing helpers here:
1. Fixed functions such as DrawColouredpoly. I have *not* implemented a DrawTexturedPoly. I may perhaps do this at a later stage
2. There is a "fluent" style drawing interface that can be used to build draw commands incrementally, and then modify and reuse them. It is a little bit heavier in terms of object creation (ease of use versus performance), but should be suitable. To draw a Textured circle, it would be the following:

```
            textureBrush = TextureBrush(texture, textureCoordinateMode, textureScaling, textureTilingScale);
            //d is the drawing object, that can be modified and used at any time to generate a draw request for the shape it describes
            var d = draw.Helpers.Construct().Textured(textureBrush, mixColour).Poly(centrePosition, numSides, radius).Filled();
            draw.Draw(drawStage, d.GenerateDrawRequest(coordinateSpace, depth, layer)); //Could also use d.SubmitDraw()

///where
/// <summary>
        /// Descriptor for Texturing Brush 
        /// </summary>
        /// <param name="texture">Texture Reference</param>
        /// <param name="textureMode">Wrap Texture Coordinates - Mirror or Repeat</param>
        /// <param name="textureScaling">Is the Texture tiled or stretched across the shape</param>
        /// <param name="tilingScale">When tiling, ratio between shape pixel and texture pixel sizes</param>

```
(Please see the project Draw_FluentInterfaceDrawingHelper in the yak2d samples repo)

Apologies if any syntax errors in the above, I am not on a system where i can check the code. will do so later

Note that this fluent approach will place the centre of the texture at the centre of the shape. 

Let me know if the above makes sense, or is useful. If you need help creating a simpler or custom textured shape drawing function I can help

Thanks!

**Comment by limocute** [comment]
Thank you for your answer. It's very useful to me. I've successfully realized it
